version: '3.8'

services:
  developerstore-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    volumes:
      - .:/src
      - ~/.aspnet/https:/https:ro
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5000:80"
      - "5001:443"
      - "5002:5002" # Para debug