version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container-developer-store
    environment:
      POSTGRES_DB: DeveloperStore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@passRRamb11R@
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local